#!/usr/bin/env python3
"""Build cloudflare/seed.sql from data/rainy_day_lookup.csv (or rainfall.db)."""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "rainy_day_lookup.csv"
DB_PATH = ROOT / "data" / "rainfall.db"
OUT_PATH = Path(__file__).resolve().parent / "seed.sql"
BATCH = 80

COLS = [
    "date",
    "district_en",
    "district_zh",
    "assignment",
    "source_station_codes",
    "n_stations",
    "n_stations_with_data",
    "n_nonzero_stations",
    "pct_nonzero_stations",
    "rainfall_mm",
    "wet_limit_mm",
    "data_ok",
    "is_rainy",
    "prev_date",
    "prev_rainfall_mm",
    "prev_data_ok",
    "prev_is_rainy",
    "two_day_rainy",
    "refreshed_at_utc",
]
INT_COLS = {
    "n_stations",
    "n_stations_with_data",
    "n_nonzero_stations",
    "data_ok",
    "is_rainy",
    "prev_data_ok",
    "prev_is_rainy",
    "two_day_rainy",
}
REAL_COLS = {"pct_nonzero_stations", "rainfall_mm", "wet_limit_mm", "prev_rainfall_mm"}


def coverage_from_lookup(df: pd.DataFrame) -> dict:
    dates = pd.to_datetime(df["date"], errors="coerce")
    refreshed = df["refreshed_at_utc"].dropna() if "refreshed_at_utc" in df.columns else pd.Series(dtype=str)
    min_date = dates.min()
    max_date = dates.max()
    return {
        "rows": int(len(df)),
        "districts": int(df["district_en"].nunique()) if len(df) else 0,
        "min_date": None if dates.empty or pd.isna(min_date) else pd.Timestamp(min_date).strftime("%Y-%m-%d"),
        "max_date": None if dates.empty or pd.isna(max_date) else pd.Timestamp(max_date).strftime("%Y-%m-%d"),
        "refreshed_at_utc": None if refreshed.empty else str(refreshed.max()),
    }


def load() -> pd.DataFrame:
    if DB_PATH.exists():
        df = pd.read_sql_query("SELECT * FROM rainy_day_lookup", sqlite3.connect(DB_PATH))
    elif CSV_PATH.exists():
        df = pd.read_csv(CSV_PATH)
    else:
        raise FileNotFoundError("run update_rainfall.py first")
    return df


def sql_lit(value, col: str) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)) or value == "":
        return "NULL"
    if col in INT_COLS:
        return str(int(value))
    if col in REAL_COLS:
        return repr(float(value))
    text = str(value)
    if col in {"date", "prev_date"}:
        text = text[:10]
    return "'" + text.replace("'", "''") + "'"


def main() -> int:
    df = load()
    missing = [c for c in COLS if c not in df.columns]
    if missing:
        raise SystemExit(f"lookup table missing columns: {missing}")
    cov = coverage_from_lookup(df)
    lines = [
        "-- Generated by build_seed.py. Do not edit by hand.",
        "DELETE FROM rainy_day_lookup;",
        "DELETE FROM pipeline_meta;",
    ]
    n = len(df)
    for start in range(0, n, BATCH):
        chunk = df.iloc[start : start + BATCH]
        values = []
        for _, row in chunk.iterrows():
            vals = ",".join(sql_lit(row[c], c) for c in COLS)
            values.append(f"({vals})")
        lines.append(
            "INSERT INTO rainy_day_lookup (" + ",".join(COLS) + ") VALUES\n"
            + ",\n".join(values)
            + ";"
        )
    lines.append(
        "INSERT INTO pipeline_meta (id, rows, districts, min_date, max_date, refreshed_at_utc) VALUES ("
        f"1,{cov['rows']},{cov['districts']},"
        f"{sql_lit(cov['min_date'], 'date')},"
        f"{sql_lit(cov['max_date'], 'date')},"
        f"{sql_lit(cov['refreshed_at_utc'], 'refreshed_at_utc')}"
        ");"
    )
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH} ({n} rows, batch={BATCH})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
