#!/usr/bin/env python3
"""Build cloudflare/seed.sql from data/rainy_day_lookup.csv (or rainfall.db)."""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "rainy_day_lookup.csv"
DB_PATH = ROOT / "data" / "rainfall.db"
OUT_PATH = Path(__file__).resolve().parent / "seed.sql"
BATCH = 80

COLS = [
    "date",
    "district_en",
    "district_zh",
    "assignment",
    "source_station_codes",
    "n_stations",
    "n_stations_with_data",
    "n_nonzero_stations",
    "pct_nonzero_stations",
    "rainfall_mm",
    "wet_limit_mm",
    "data_ok",
    "is_rainy",
    "prev_date",
    "prev_rainfall_mm",
    "prev_data_ok",
    "prev_is_rainy",
    "two_day_rainy",
    "refreshed_at_utc",
]
INT_COLS = {
    "n_stations",
    "n_stations_with_data",
    "n_nonzero_stations",
    "data_ok",
    "is_rainy",
    "prev_data_ok",
    "prev_is_rainy",
    "two_day_rainy",
}
REAL_COLS = {"pct_nonzero_stations", "rainfall_mm", "wet_limit_mm", "prev_rainfall_mm"}


def load() -> pd.DataFrame:
    if DB_PATH.exists():
        df = pd.read_sql_query("SELECT * FROM rainy_day_lookup", sqlite3.connect(DB_PATH))
    elif CSV_PATH.exists():
        df = pd.read_csv(CSV_PATH)
    else:
        raise FileNotFoundError("run update_rainfall.py first")
    return df


def sql_lit(value, col: str) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)) or value == "":
        return "NULL"
    if col in INT_COLS:
        return str(int(value))
    if col in REAL_COLS:
        return repr(float(value))
    text = str(value)
    if col in {"date", "prev_date"}:
        text = text[:10]
    return "'" + text.replace("'", "''") + "'"


def main() -> int:
    df = load()
    missing = [c for c in COLS if c not in df.columns]
    if missing:
        raise SystemExit(f"lookup table missing columns: {missing}")
    lines = [
        "-- Generated by build_seed.py. Do not edit by hand.",
        "DELETE FROM rainy_day_lookup;",
    ]
    n = len(df)
    for start in range(0, n, BATCH):
        chunk = df.iloc[start : start + BATCH]
        values = []
        for _, row in chunk.iterrows():
            vals = ",".join(sql_lit(row[c], c) for c in COLS)
            values.append(f"({vals})")
        lines.append(
            "INSERT INTO rainy_day_lookup (" + ",".join(COLS) + ") VALUES\n"
            + ",\n".join(values)
            + ";"
        )
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH} ({n} rows, batch={BATCH})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
